### ISSUE TITLE
Doesn't seem to affect teleport

### ISSUE THREAD

**Issue by JZ6** [CrystalFerrai/ValheimMods#1]
https://valheim.thunderstore.io/package/LVH-IT/FasterTeleportation/0.3.1/

this mod seems to work for teleporting with mods like https://valheim.thunderstore.io/package/exel80/MapTeleporter/1.0.0/

**Comment by CrystalFerrai** [comment]
Looks like MapTeleporter places the player under the world and causes the game to wait 15 seconds before fixing their position. i have accounted for this in version 1.1.0 of ProperPortals by shortening that 15 second timeout to 0.5 seconds. i also opened an issue with MapTeleporter showing them how to fix the issue of placing the player under the world (which happens to also make the player wet).

**Comment by JZ6** [comment]
awesome work man!
