### ISSUE TITLE
QoL Request - Pathfinder - show calculations with DisplayCurrentRadiusValue = true

### ISSUE THREAD

**Issue by CruxCraft** [CrystalFerrai/ValheimMods#10]
It would be nice to see the calculations that are being done with DisplayCurrentRadiusValue = true

Some of the multipliers don't seem to play with one another very well (ie forest is the same no mater what time of night etc). I was hoping to make the map fill in almost nothing during the latest hours and during storms, but not sure if all the multipliers are being applied in all situations...

Thanks =] Enjoying this otherwise

**Comment by CrystalFerrai** [comment]
I am not doing any significant work on Valheim mods at this time. I may come bask to this in the future, but I am focusing on other projects now.

**Comment by CrystalFerrai** [comment]
I have now added a new option to display the values being used in the radius calculation. This option is called `DisplayVariables`.
