### ISSUE TITLE
Bug report - Sated

### ISSUE THREAD

**Issue by dredknot** [CrystalFerrai/ValheimMods#12]
Sated seems to be using the old food stats from before Hearth & Home update. Otherwise seems to work as intended.

**Comment by CrystalFerrai** [comment]
Food stats are read directly from food items the same way they are read in the unmodded game. I cannot see any way old food stats could be loaded since they don't even exist. I did fix some other issues with the health and stamina calculations in 1.1.4 which led to incorrect stamina totals.
