### ISSUE TITLE
Very Poor Optimization - Pathfinder

### ISSUE THREAD

**Issue by lupuleasa-core** [CrystalFerrai/ValheimMods#14]
Many people have been observing pathfinder is using too many resources

https://www.reddit.com/r/ModdedValheim/comments/syx40s/comment/hy3zf4b/?utm_source=share&utm_medium=web2x&context=3

Can the polling rate be changed or something

**Comment by CrystalFerrai** [comment]
I gathered some timing info. This mod updates the range approximately 4 times per second and takes approximately 0.3 ms per update. This means it takes approximately 0.12 ms per second of cpu time. If the game runs at 60 fps without this mod, it would run at 59.6 fps with this mod. A loss of 0.4 fps may be significant, but not enough for me to want to try to profile and optimize this. Results may be slightly worse on slower CPUs, but relatively speaking this is a drop in a bucket and not worth the effort try to make the drop just a little smaller.
