### ISSUE TITLE
ProperPortals - Item description update

### ISSUE THREAD

**Issue by pjmichor** [CrystalFerrai/ValheimMods#15]
Can you look at removing the "cannot be teleported" text that appears on items when this mod is installed? The mod works, just could be confusing for players that aren't aware it's active (like on a server).

**Comment by CrystalFerrai** [comment]
I see the value in this request (and even considered it when creating the mod), but it is not worth the effort in my opinion. I am cleaning up old issues, so going to close this as unplanned.
