### ISSUE TITLE
Mistlands update?

### ISSUE THREAD

**Issue by pjmichor** [CrystalFerrai/ValheimMods#17]
Hello!

Do you plan to update the various mods to be compatible with Mistlands and its new items?

Thank you!

**Comment by MrJoshua023** [comment]
Looks like Sated is preventing the new Eitr foods from giving any Eitr.  I restarted with no mods, worked fine.  Started again with only Sated disabled.  Worked as well.

**Comment by CrystalFerrai** [comment]
Mods have all been updated and should now be compatible. If any issues are discovered, please enter them individually as new issues.
