### ISSUE TITLE
betterchat

### ISSUE THREAD

**Issue by vitalikbyrevich** [CrystalFerrai/ValheimMods#18]
Good afternoon. Is it not possible to add pictograms for inclusion (whisper, shout, say)? In order not to enter "/s,/w", but simply press the icon once. There was such a mod - KGChat, but the author does not want to repair it for updating the game.

**Comment by CrystalFerrai** [comment]
The goal of BetterChat is to fix issues with the game's built-in chat system. It is not a chat replacement or an overhaul, just some little tweaks to the existing chat. While it would probably be possible to add these button, that goes beyond the scope of what I want to do with this mod at this time.
