### ISSUE TITLE
Pathfinder 2.0.2 release bug

### ISSUE THREAD

**Issue by GoogleMaster** [CrystalFerrai/ValheimMods#2]
Pathfinder mod has released with uncommented #define DEBUG_SHOW_OVERLAY line at Pathfinder/PathfinderPlugin.cs (check 8475ba4e77d7ed18512bc343c8ff5566cf77b35b)
so everybody sees debug hud

**Comment by CrystalFerrai** [comment]
Fixed in 2.0.3. Good reminder why I shouldn't release things when I am sleepy.
