### ISSUE TITLE
Thanks for making this repo public

### ISSUE THREAD

**Issue by teauxfu** [CrystalFerrai/ValheimMods#20]
It's really useful as an example to learn from. I was kind of surprised at how short the code for DigDeeper is, but it was interesting to read over. Being more familiar with the game's codebase, can you speculate about why the devs might have chosen the vanilla defaults? Particularly with regards to digging, it just seems weird that they made the choice to cap it at such a low value by default. Have you encountered any weird behavior at extreme height differences?

Anyway, thanks again. Cheers

**Comment by CrystalFerrai** [comment]
I have not seen any particularly weird behavior, just minor things. Digging below sea level (Y=30) leads to encountering sea water seemingly anywhere on the map. You cannot dig underwater unless you go into debug mode, which I used to test digging as low as -5 without issue. Also, a deep enough hole will kill you from fall damage if you fall into it.  I never found anything game breaking.

The main thing that pushed me into making the mod was to be able to fully dig out copper nodes. It always bothered me that the default depth limit is 8 when copper nodes can go as deep as 12-16.
