### ISSUE TITLE
Sated

### ISSUE THREAD

**Issue by D-A-R-K-N-E-S-S** [CrystalFerrai/ValheimMods#21]
Is the mod client side only or server-client? No mention of this on the thunderstore page.

Thank you.

**Comment by CrystalFerrai** [comment]
All of my mods are client only mods. You can add them to a server, but they won't do anything there. I will look into adding this info to Thunderstore at some point.

**Comment by D-A-R-K-N-E-S-S** [comment]
Thank you for clearing this up, appreciate the mod.
