### ISSUE TITLE
Feature Request: Serversync Config

### ISSUE THREAD

**Issue by Gladiator1337** [CrystalFerrai/ValheimMods#24]
Hello,

we are using your Betterchat mod on our PVP Server, but every Player with a little Skill can set Shoutping manually at his config from False to true.

My Question is could this be Serversynced because than everybody has the same config and can not edit it by himself.

Thx

Best Regards

Gladiator1337

**Comment by CrystalFerrai** [comment]
Better Chat is a client only mod.  There is no plan to add any sort of server syncing.
