### ISSUE TITLE
Problems after patch 0.216.9

### ISSUE THREAD

**Issue by SashaKillmagik** [CrystalFerrai/ValheimMods#25]
Does not draw progress on the map and gives such an error

[Error  : Unity Log] MethodAccessException: Method `Player.GetPlayersInRange(UnityEngine.Vector3,single,System.Collections.Generic.List`1<Player>)' is inaccessible from method `Pathfinder.PathfinderPlugin+Minimap_Patches.GetExploreRadius(Player)'
Stack trace:
Pathfinder.PathfinderPlugin+Minimap_Patches.GetExploreRadius (Player player) (at <9610ae6f33604c74b12ea9808249d67f>:0)
(wrapper dynamic-method) Minimap.DMD<Minimap::UpdateExplore>(Minimap,single,Player)
(wrapper dynamic-method) Minimap.DMD<Minimap::Update>(Minimap)

**Comment by CrystalFerrai** [comment]
This is now fixed in Pathfinder version 2.0.8.
