### ISSUE TITLE
Question no issue

### ISSUE THREAD

**Issue by majesticuni** [CrystalFerrai/ValheimMods#27]
I really enjoy the DigDeeper mod and its amazing, but I was wanting to know if there was a way to get in contact with you in case your mod breaks etc or theres issue? The mod hasnt been updated for 7months since the latest update and im sure the new PTB will break alot of mods once again, so was curious if there an easy way to get in contact with you incase ur mods break etc

**Comment by CrystalFerrai** [comment]
You can always file issues here on Github. I make no promises about the timeliness of updates, but I see issues filed here and will look into them as I am able.
