### ISSUE TITLE
Suggestion - Reduce Rested per distance teleported?

### ISSUE THREAD

**Issue by Oosquai** [CrystalFerrai/ValheimMods#28]
Hi Crystal!
Just an idea I've been toying with.  I'm trying to promote my players building more bases around the world by creating a close-to-home type of effect.  I don't want to strip Rested completely when teleporting, since that prevents doing a short teleport to skip a tedious run, like up a mountain.  Would you consider a config option like this?  Defaulting to 0 turns it off, just like you do with other settings.

Reduce Rested buff by X seconds for every 100 distance traveled when teleporting = 0

Full transparency, I've asked the same of Alcan for Comfort Tweaks, but I'm not sure they're reading any messages or still making updates.

Thank you!

**Comment by CrystalFerrai** [comment]
Sorry, this is not something that I am interested in doing at this time.

**Comment by Oosquai** [comment]
No worries, thanks for the reply!  Happy modding and happy holidays!
