### ISSUE TITLE
1.0.6.0 Breaks on Current Version

### ISSUE THREAD

**Issue by Morpheus1101** [CrystalFerrai/ValheimMods#29]
With the below, when you load into the game, the menu screen etc is all broken an the console continuously scrolls red.
-----------------------------------------------------

[Info   :   BepInEx] Loading [Underwater 1.0.6.0]
[Error  : Unity Log] MissingMethodException: Method not found: ZInput/ButtonDef .ZInput.AddButton(string,UnityEngine.KeyCode,single,single,bool,bool)
Stack trace:
Underwater.UnderwaterPlugin.Awake () (at <c3ba07d46e714f668e8145d365349e90>:0)
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.GameObject:.cctor()
Fishlabs.Common.SingletonMonoBehaviour`1:get_Instance()
Fishlabs.PlatformManagerInitializer:OnRuntimeMethodLoad()

**Comment by CrystalFerrai** [comment]
Fixed now in Underwater 1.0.7 and CrystalLib 1.1.0
