### ISSUE TITLE
Underwater breaks menu

### ISSUE THREAD

**Issue by Der-Orso** [CrystalFerrai/ValheimMods#37]
With Underwater implemented, menuing is broken, game cannot start. See attachment(s): 
![menu](https://github.com/user-attachments/assets/7f7a4b99-005e-4747-88c7-1ee30530cb3a)
![menu](https://github.com/user-attachments/assets/74b240bc-d07b-4a53-bb33-62234e1d8fbf)
Sorry for the double-upload

**Comment by CrystalFerrai** [comment]
Thank you for the report. I am currently busy with other things and do not have time to update Valheim mods. I will look into all reported issues the next time I get a chance, hopefully within a few weeks.

**Comment by CrystalFerrai** [comment]
Version 1.0.8 has been released with a fix for this issue.
