### ISSUE TITLE
New Valheim 0.150.3 terrain system makes DigDeeper not function

### ISSUE THREAD

**Issue by UntoldForce** [CrystalFerrai/ValheimMods#4]
Valheim changed the terrain system in 0.150.3 so that any terrain changes made after that patch would be updated to the new system. This prevents DigDeeper from functioning.

Issue: DigDeeper should allow the player to dig terrain or raise terrain to the configurable limit
Problem: Attempts to dig/raise beyond the normal limit will fail
Cause: New terrain system introduced in recent patch
Repro: 100% on game versions > 0.150.3

**Comment by KingTedanor** [comment]
I also noticed this issue - will there be a fix?

**Comment by CrystalFerrai** [comment]
I have a lot of other things going on right now. I will look into this when I have a chance.

**Comment by CrystalFerrai** [comment]
New release of DigDeeper (1.1.0) fixes this issue.
