### ISSUE TITLE
PathFinder: GetShipControl is no longer a function

### ISSUE THREAD

**Issue by Dalayeth** [CrystalFerrai/ValheimMods#5]
This causes an error in Hearth and Home and makes it so no area is discovered.

Line 210:
`if (players.Any(p => p.GetShipControl() != null))`
Needs to be changed to.
`if (players.Any(p => p.IsAttachedToShip() == true))`

This stops the errors and allows the map to discover again. I haven't actually tested this with a ship though. This function works a little different. Like it says this is attached at all not just controlling so we are looking for players withing 21 units of anyone who is attached to a ship. Shouldn't cause problems but slight difference.

**Comment by KairuByte** [comment]
I can confirm this seems to handle the issue, and I did not see any issues when playing solo.

**Comment by CrystalFerrai** [comment]
This is now fixed in version 2.0.4.
