### ISSUE TITLE
Request - NexusMods

### ISSUE THREAD

**Issue by CruxCraft** [CrystalFerrai/ValheimMods#7]
Would you be able to list your mods on NexusMods as well?

NexuxMods search is horrible, but their interface is better and its where I go to update mods etc.

LOVE that BetterChat removes those location pings from the map when shouting.
(testing BetterChat shortly along with Pathfinder... torn on DigDeeper but maybe our next world).

Thanks & I hope I can see these there, unless there was a reason they aren't.

**Comment by CrystalFerrai** [comment]
All mods are hosted at [Thunderstore](https://valheim.thunderstore.io/package/Crystal/). I don't want to deal with keeping mods updated in multiple places, and I prefer Thunderstore over Nexus.
