### ISSUE TITLE
Feature Request - BetterChat - Silent Pings

### ISSUE THREAD

**Issue by CruxCraft** [CrystalFerrai/ValheimMods#8]
Feature Request - BetterChat - Silent Pings:

An option to stop the ping command from spamming the chat box, but otherwise work normally...

**Comment by CrystalFerrai** [comment]
I am not doing any significant work on Valheim mods at this time. I may come bask to this in the future, but I am focusing on other projects now.

In the meantime, please describe what you are asking for. I do not see map pings in chat, and the /ping command needs to report something in chat, else it is useless. I do not know of any other ping command.

**Comment by CrystalFerrai** [comment]
This has been open for over a year. I am closing this out as part of an issue clean up I am doing.
