### ISSUE TITLE
Feature Request - BetterChat - Mute Player in config

### ISSUE THREAD

**Issue by CruxCraft** [CrystalFerrai/ValheimMods#9]
Feature Request - BetterChat - Mute Player:
ability to mute players in config (to filter out noisy mods that shout to chat)

**Comment by CrystalFerrai** [comment]
I am not doing any significant work on Valheim mods at this time. I may come bask to this in the future, but I am focusing on other projects now.

In the meantime, please add more info to this request. I do not understand what you are asking for. Do you mean a list of specific player names to mute, or something else?

**Comment by CrystalFerrai** [comment]
This has been open for over a year. I am closing this out as part of an issue clean up I am doing.
